spring.application.name=management
server.port=8080
 
spring.datasource.url=jdbc:mysql://localhost:3306/project_manager
spring.datasource.username=root
spring.datasource.password=ALIEN_MO00079

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true